In [1]:
import numpy as np

# 1. 创建形状为 3×4 的随机矩阵 X，元素服从标准正态分布
# np.random.randn() 生成标准正态分布（均值0，方差1）的随机数
X = np.random.randn(3, 4)
print("=== 矩阵 X (3×4) ===")
print(X)
print()

# 2. 创建形状为 4×2 的全 1 矩阵 Y
Y = np.ones((4, 2))
print("=== 矩阵 Y (4×2) ===")
print(Y)
print()

# 3. 计算矩阵乘法 Z = X × Y
# NumPy 中矩阵乘法推荐用 @ 运算符或 np.dot()
Z = X @ Y
# 也可以写成：Z = np.dot(X, Y)
print("=== 矩阵 Z = X × Y (3×2) ===")
print(Z)
print()

# 4. 输出 Z 的第一行和第二列交叉处的元素，以及 Z 的第 2 行所有元素
# 注意：NumPy 索引从 0 开始
# 第一行、第二列：Z[0, 1]
# 第 2 行所有元素：Z[1, :] （索引为1）
print("=== 第4问输出 ===")
print("Z 的第一行和第二列交叉处的元素：", Z[0, 1])
print("Z 的第 2 行所有元素：", Z[1, :])
print()

# 5. 计算 Z 的 Frobenius 范数
# np.linalg.norm() 默认就是 Frobenius 范数（矩阵的2范数）
frobenius_norm = np.linalg.norm(Z)
print("=== 第5问输出 ===")
print("Z 的 Frobenius 范数：", frobenius_norm)

=== 矩阵 X (3×4) ===
[[-0.13293514  0.26776253 -1.61308032  1.09174349]
 [-0.34465881  0.11208256 -1.27607295 -0.41435177]
 [-0.86772847 -3.19875491 -1.34546632  0.40235265]]

=== 矩阵 Y (4×2) ===
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

=== 矩阵 Z = X × Y (3×2) ===
[[-0.38650943 -0.38650943]
 [-1.92300097 -1.92300097]
 [-5.00959705 -5.00959705]]

=== 第4问输出 ===
Z 的第一行和第二列交叉处的元素： -0.38650943374485425
Z 的第 2 行所有元素： [-1.92300097 -1.92300097]

=== 第5问输出 ===
Z 的 Frobenius 范数： 7.608335540201701
